apiVersion: v2
name: workshop-test
description: A Helm chart for Kubernetes
type: application
dependencies:
  - name: user19-hello-world:1.0.0
    repository: oci://ghcr.io/lotemsier/helm
    version: "1.0.0"
    alias: deploy1
version: 1.0.0
appVersion: "1.0.0"